### PR TITLE
feat: Add charts for stored, solidifier, scheduler and booker and simplify memStats

### PR DESCRIPTION
**Pull request by jkrvivian**
# Description of change

* Simplify mem usage of dashboard and align to grafana
* Add a chart for stored, solidifier, scheduler and booker MPS

image

## Type of change
- Enhancement

## Change checklist

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by lzpap — CHANGES_REQUESTED** [review]
Since you added a new ws msg type, please update the ws msg definitions in the analysis dashboard (`plugins/analysis/dashboard/frontend/src/app/models/ws/WSMsgTypeDashboard.ts`) too, otherwise the mana page will break there.

**Review by acha-bill — APPROVED** [review]
LGTM.

**Comment by acha-bill** [comment]
@jkrvivian what if we combined all the datasets in 1 chart?

**Comment by jkrvivian** [comment]
@acha-bill that sounds good! we can then tell the difference in one chart rather than scrolling up and down. :stuck_out_tongue_closed_eyes:

**Review by lzpap — APPROVED** [review]

**Pull request merged**
