### PR TITLE
enable remote debugging on test

### LINKED ISSUE #2019: Remote debugger option
Launch a delve debugger.
Master docker file has it already.
Run the other one image with delve debugger instead of the default one.

### PR DESCRIPTION
**Pull request by GalRogozinski**
# Description of change

Fixes #2019 by building an image that runs `dlv`, utilizing a variable that already exists in our DockerFile.

Documentation will be added only after  #2018 Will be done. Then we will use the `socat` container to forward debugging calls.

## Type of change

- Enhancement (a non-breaking change which adds functionality)

### CODE REVIEW

**Comment by karimodm** [comment]
@GalRogozinski: can you please add to the port forwarding issue to also expose the debug port using socat? So this issue can be considered complete.

**Comment by GalRogozinski** [comment]
@karimodm 
that's on another PR that is currently tested

**Comment by karimodm** [comment]
> @karimodm that's on another PR that is currently tested

Which one?

**Review by karimodm — APPROVED** [review]
LGTM

**Review by jkrvivian — APPROVED** [review]

**Pull request merged**
