### PR TITLE
Add json and shell annotations for better readability

### PR DESCRIPTION
**Pull request by daria305**
Add `shell` and `json` to docs to improve readability, work started in #1981

### CODE REVIEW

**Comment by JanOonk** [comment]
Here a small scan of all .md files:

```
Found 49 files matching *.md in /temp/documentation
\README.md: 8 codesnippets found
  3 Unique Types: ```, ```console, ```json
  ```: 1x
  ```console: 5x
  ```json: 2x
\docs\faq.md: 0 codesnippets found
\docs\welcome.md: 0 codesnippets found
\docs\apis\autopeering.md: 3 codesnippets found
  3 Unique Types: ```go, ```json, ```shell
  ```go: 1x
  ```json: 1x
  ```shell: 1x
\docs\apis\client_lib.md: 3 codesnippets found
  1 Unique Types: ```
  ```: 3x
\docs\apis\communication.md: 14 codesnippets found
  3 Unique Types: ```go, ```json, ```shell
  ```go: 4x
  ```json: 5x
  ```shell: 5x
\docs\apis\dRNG.md: 10 codesnippets found
  3 Unique Types: ```go, ```json, ```shell
  ```go: 3x
  ```json: 3x
  ```shell: 4x
\docs\apis\faucet.md: 4 codesnippets found
  3 Unique Types: ```go, ```json, ```shell
  ```go: 1x
  ```json: 2x
  ```shell: 1x
\docs\apis\info.md: 4 codesnippets found
  3 Unique Types: ```go, ```json, ```shell
  ```go: 1x
  ```json: 1x
  ```shell: 2x
\docs\apis\ledgerstate.md: 41 codesnippets found
  3 Unique Types: ```go, ```json, ```shell
  ```go: 14x
  ```json: 14x
  ```shell: 13x
\docs\apis\mana.md: 35 codesnippets found
  2 Unique Types: ```go, ```shell
  ```go: 13x
  ```shell: 22x
\docs\apis\manual_peering.md: 10 codesnippets found
  3 Unique Types: ```go, ```json, ```shell
  ```go: 3x
  ```json: 4x
  ```shell: 3x
\docs\apis\snapshot.md: 1 codesnippets found
  1 Unique Types: ```shell
  ```shell: 1x
\docs\apis\spammer.md: 3 codesnippets found
  3 Unique Types: ```go, ```json, ```shell
  ```go: 1x
  ```json: 1x
  ```shell: 1x
\docs\apis\tools.md: 27 codesnippets found
  5 Unique Types: ```, ```csv, ```go, ```json, ```shell
  ```: 9x
  ```csv: 1x
  ```go: 2x
  ```json: 2x
  ```shell: 13x
\docs\apis\webAPI.md: 8 codesnippets found
  1 Unique Types: ```
  ```: 8x
\docs\implementation_design\configuration_parameters.md: 5 codesnippets found
  3 Unique Types: ```bash, ```go, ```json
  ```bash: 1x
  ```go: 3x
  ```json: 1x
\docs\implementation_design\event_driven_model.md: 4 codesnippets found
  1 Unique Types: ```go
  ```go: 4x
\docs\implementation_design\object_storage.md: 11 codesnippets found
  1 Unique Types: ```go
  ```go: 11x
\docs\implementation_design\packages_plugins.md: 0 codesnippets found
\docs\implementation_design\plugin.md: 10 codesnippets found
  1 Unique Types: ```go
  ```go: 10x
\docs\protocol_specification\glossary.md: 0 codesnippets found
\docs\protocol_specification\overview.md: 0 codesnippets found
\docs\protocol_specification\protocol.md: 0 codesnippets found
\docs\teamresources\analysis_dashboard.md: 0 codesnippets found
\docs\teamresources\guidelines.md: 2 codesnippets found
  1 Unique Types: ```go
  ```go: 2x
\docs\teamresources\local_development.md: 3 codesnippets found
  2 Unique Types: ```, ```json
  ```: 2x
  ```json: 1x
\docs\teamresources\release.md: 0 codesnippets found
\docs\tooling\docker_private_network.md: 11 codesnippets found
  4 Unique Types: ```, ```bash, ```json, ```shell
  ```: 4x
  ```bash: 5x
  ```json: 1x
  ```shell: 1x
\docs\tooling\integration_tests.md: 3 codesnippets found
  3 Unique Types: ```, ```go, ```yaml
  ```: 1x
  ```go: 1x
  ```yaml: 1x
\docs\tooling\overview.md: 0 codesnippets found
\docs\tutorials\custom_dRNG.md: 0 codesnippets found
\docs\tutorials\dApp.md: 10 codesnippets found
  2 Unique Types: ```, ```go
  ```: 2x
  ```go: 8x
\docs\tutorials\manual_peering.md: 1 codesnippets found
  1 Unique Types: ```json
  ```json: 1x
\docs\tutorials\monitoring.md: 29 codesnippets found
  4 Unique Types: ```, ```bash, ```json, ```yaml
  ```: 17x
  ```bash: 6x
  ```json: 3x
  ```yaml: 3x
\docs\tutorials\obtain_tokens.md: 1 codesnippets found
  1 Unique Types: ```go
  ```go: 1x
\docs\tutorials\send_transaction.md: 22 codesnippets found
  3 Unique Types: ```go, ```shell, ```shell script
  ```go: 20x
  ```shell: 1x
  ```shell script: 1x
\docs\tutorials\setup.md: 55 codesnippets found
  4 Unique Types: ```, ````, ```bash, ```yaml
  ```: 35x
  ````: 1x
  ```bash: 14x
  ```yaml: 5x
\docs\tutorials\static_identity.md: 3 codesnippets found
  3 Unique Types: ```, ```json, ```yml
  ```: 1x
  ```json: 1x
  ```yml: 1x
\docs\tutorials\wallet_library.md: 83 codesnippets found
  3 Unique Types: ```, ```bash, ```json
  ```: 15x
  ```bash: 66x
  ```json: 2x
\docs\protocol_specification\components\advanced_outputs.md: 0 codesnippets found
\docs\protocol_specification\components\autopeering.md: 4 codesnippets found
  2 Unique Types: ```, ```vbnet
  ```: 2x
  ```vbnet: 2x
\docs\protocol_specification\components\congestion_control.md: 0 codesnippets found
\docs\protocol_specification\components\consensus_mechanism.md: 2 codesnippets found
  1 Unique Types: ```
  ```: 2x
\docs\protocol_specification\components\ledgerstate.md: 1 codesnippets found
  1 Unique Types: ```vbnet
  ```vbnet: 1x
\docs\protocol_specification\components\mana.md: 16 codesnippets found
  1 Unique Types: ```go
  ```go: 16x
\docs\protocol_specification\components\markers.md: 2 codesnippets found
  1 Unique Types: ```go
  ```go: 2x
\docs\protocol_specification\components\overview.md: 0 codesnippets found
\docs\protocol_specification\components\tangle.md: 3 codesnippets found
  2 Unique Types: ```, ```go
  ```: 2x
  ```go: 1x
```

**Comment by daria305** [comment]
That's done, most of them for sure have been updated, you can rerun if you want, but I left some empty code-snippets for purpose whenever there are console outputs because it looks better without 'shell'.

**Comment by JanOonk** [comment]
- I noticed one typo in `\docs\apis\mana.md`: `josn` instead of `json`
- Also not all `bash` were replaced with `shell`.
- In `docs/tutorials/monitoring.md` the content of `prometheus.service` is not `yaml` but plain text so use \```
- Maybe for consistency use `shell` instead of the aliases `bash` and `shell scri
pt`. All are the same.

For more difference/details see WinMerge report for more details. (rename to `.html`)

[difference.html.txt](https://github.com/iotaledger/goshimmer/files/7925984/difference.html.txt)

**Comment by JanOonk** [comment]
I scanned the whole repo and noticed another error:
In `tools\entry-node\README.md` use `shell` instead of `sh` which isn't an alias and doesn't work.

Here is the complete report with added overall stats to check uniqueness of used codesnippet types.
[reportOverWholeRepoIncludingMoreStats.txt](https://github.com/iotaledger/goshimmer/files/7926159/reportOverWholeRepoIncludingMoreStats.txt)

**Comment by daria305** [comment]
@JanOonk check now :)

**Comment by JanOonk** [comment]
Whole repo scanned:

Found 64 files matching *.md in /temp/goshimmer-docs-update-docs-annotations v2

 Unique codesnippet types found: 9
     1x found in   1 file(s): ```diff
   503x found in  42 file(s): ```
     3x found in   1 file(s): ```bash
   211x found in  23 file(s): ```shell
    61x found in  22 file(s): ```json
   133x found in  25 file(s): ```go
     2x found in   1 file(s): ```csv
     9x found in   4 file(s): ```yaml
     3x found in   2 file(s): ```vbnet

More details:
[report v2.txt](https://github.com/iotaledger/goshimmer/files/7939912/report.v2.txt)

**Comment by daria305** [comment]
ok, all should look better now, thanks for help @JanOonk 
We need to keep repo clean in future READMEs though.

**Comment by JanOonk** [comment]
No problem.
What do you mean with `We need to keep repo clean in future READMEs though.`

Btw if you want I can make my repository with the tool I made public so you can use it for other repo's or in the future when new .md files are created or modified so you can check it yourself. Let me know.

**Comment by daria305** [comment]
Just generally, anyone who adds new resources. But sure with your tool the general check could be quite fast

**Comment by JanOonk** [comment]
Let me clean it up a bit first. I will also make some .NET6 cross platform builds.

**Review by jkrvivian — APPROVED** [review]

**Comment by JanOonk** [comment]
@daria305 
You can find the C# source and .net6 build for multiple platforms here:
https://github.com/JanOonk/ScanMarkdownFilesForCodeSnippets

**Pull request merged**
