### PR TITLE
Improve volumes in docker-compose files

### PR DESCRIPTION
**Pull request by piotrm50**
# Description of change

Add missing prometheus.yml file for running DevNet node in Docker.

Improve volumes in docker-compose files for both local Docker network as well as DevNet node. 
Use Docker volumes instead of mapping path inside of repository. Makes it easier to clean volumes if necessary and allows users to more precisely configure them.

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Ran both docker-compose files locally. 

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by NicolasVautrin** [comment]
impossible to use azure container instance with actual setup.
Why not use an environment variable to set the timezone ?
environment:
- TZ= 'America/New_York'

root@goshimmer:/usr/local/bin# ./docker compose up -d
WARNING network outside: network.external.name is deprecated in favor of network.name 
host path ("/etc/localtime") not allowed as volume source, you need to reference an Azure File Share defined in the 'volumes' section

**Comment by NicolasVautrin** [comment]
Here some things that prevent to deploy goShimmer on azure container instance.

root@goshimmer:/usr/local/bin# ./docker compose up 
host path ("/etc/localtime") not allowed as volume source, you need to reference an Azure File Share defined in the 'volumes' section 

Why not use environment variablew to set the timezone like TZ='france/paris' 

But the more complicated is this 
https://docs.docker.com/cloud/aci-compose-features/
Azure override the wall entrypoint when we use command in docker-compose. 

I’d tried to set the whole entry point of dockerfile but /run/dlv didn’t work ,exec is not recognize, only /run/goshimmer worked. But has you imagine my container don’t keep running without 'exec --continu'

**Comment by NicolasVautrin** [comment]
Apache has something like that , to keep the container running
CMD ["apachectl", "-D",  "FOREGROUND"]

**Comment by piotrm50** [comment]
> Why not use environment variablew to set the timezone like TZ='france/paris'
We want to have a generic solution that can be used out-of-the-box without customizing it beforehand. If you need, you can change it for your deployment to use environment variable :) 

 
> But the more complicated is this https://docs.docker.com/cloud/aci-compose-features/ Azure override the whole entrypoint when we use command in docker-compose.

The goal of this docker-compose is not to be one-fits-all solution, but rather a starting point to run the node in the basic environment and have something to start with if you want to run it in more specific environment.

**Review by karimodm — APPROVED** [review]

**Pull request merged**
